name: Calbuilder
author: Santiago Lo Coco
description: Makepkg, analyze it with namcap, and output the package file and its .SRCINFO
branding:
  color: green
  icon: zap
inputs:
  pkgDir:
    description: "PKGBUILD directory relative path."
    required: false
    default: "."
  gpgPublicKey:
    description: "GPG public key that will be used to sign packages."
    required: false
    default: ""
  gpgPrivateKey:
    description: "GPG private key."
    required: false
    default: ""
  gpgPassphrase:
    description: "The GPG passphrase for the gpgPrivateKey."
    required: false
    default: ""
outputs:
  srcInfo:
    description: "Generated .SRCINFO"
  pkgFile:
    description: "Built package file."
  pkgFileSig:
    description: "Built package signature file."
runs:
  using: 'docker'
  image: 'Dockerfile'
